#服务器配置
server:
  port: 80
  servlet:
    context-path: /survey
#spring配置
spring:
  #数据源配置
  datasource:
    #配置mysql数据库
    #mysql新版驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/survey?serverTimezone=CTT
#    url: jdbc:mysql://192.168.3.129:3306/survey?serverTimezone=CTT
    username: root
    password: root
    #druid连接池配置
    druid:
    #初始化大小、最小空闲、最大激活
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#配置mybatis框架
mybatis:
  #定义Mapper接口映射文件位置
  mapper-locations: classpath:mapper/*Mapper.xml
  #定义实体类位置
  type-aliases-package: com.dave.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
#控制台打印sql语句
logging:
  level:
    com.ming.ssm.mapper: debug